<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "session_popup"
 *
 * Auto generated by Extension Builder 2020-03-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Session Popup',
    'description' => 'Configure a popup that appears once a session.',
    'category' => 'plugin',
    'author' => 'Karina Kern',
    'author_email' => 'karina@webschmiede.at',
    'state' => 'beta',
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
